# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rabbit"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Patrick Brisbin"]
  s.date = "2011-10-27"
  s.description = "A n aur helper in ruby"
  s.email = "pbrisbin@gmail.com"
  s.executables = ["rabbit"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/rabbit",
    "lib/rabbit/aur.rb",
    "lib/rabbit/json.rb",
    "lib/rabbit/package.rb",
    "lib/rabbit/pkgbuild.rb",
    "lib/threaded-each.rb",
    "rabbit.gemspec"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A n aur helper in ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

